services:
  - type: web
    name: rosa-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: MONGO_URI
        value: your_mongodb_connection_string_here
      - key: JWT_SECRET
        value: your_jwt_secret_key

  - type: web
    name: rosa-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist # or build if you're using CRA (React)
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
